# Generated by Django 2.2.5 on 2019-09-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customerId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('credit', models.IntegerField()),
                ('status', models.BooleanField()),
                ('remarks', models.CharField(max_length=1000)),
            ],
        ),
    ]
